name: CI

on:
  push:
    branches: [ continuous-integration ]
  pull_request:
    branches: [ continuous-integration ]

jobs:
  test:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: npm install and test
      run: |
        npm install
        npm test -- --coverage
